CREATE TABLE prestamos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_lector VARCHAR(255) NOT NULL,
    fecha_prestamo DATE NOT NULL,
    fecha_devolucion DATE,
    estado VARCHAR(255) NOT NULL
);

CREATE TABLE libros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    stock INTEGER NOT NULL CHECK (stock >= 0),
    prestamo_id BIGINT,
    CONSTRAINT fk_libros_prestamos
        FOREIGN KEY (prestamo_id)
        REFERENCES prestamos (id)
);
